### ISSUE TITLE
category id missing in parent view

### ISSUE THREAD

**Issue by Narmadha6790** [dreispt/library_app#1]
When tried to create an inherited view got the following  error message 
Error while validating constraint

Element '<field name="category_id">' cannot be located in parent view

Error context:
View `Contacts - Custom Is Book Author Flag`
[view_id: 726, xml_id: n/a, model: ir.model, parent_id: 33

**Comment by dreispt** [comment]
Sorry, I don't think this is an issue with the code in this repo.
